### PR TITLE
Conversion to python 3

### PR DESCRIPTION
**Pull request by danmarinescu**
Simple conversion to python 3, using 2to3
Also fixed an import to use a relative path

### CODE REVIEW

**Comment by marzetas** [comment]
I don't know if this can land into master, as we still use this in the webapp, we'll need versions in python2 and python3, which I think we haven't done yet. 

If we find a good way of doing so, I'd say that falib could follow next.

**Comment by danmarinescu** [comment]
I agree, versions 2 and 3 must be able to run in parallel. I guess there must be a pattern for seamlessly supporting versions 2 and 3 of a library

**Comment by marzetas** [comment]
Maybe a fork of this repo named`optimoroute3`, taking this as the base for it, would make sense?

**Comment by danmarinescu** [comment]
Is this the way it's done by other libs? What I know is that when I install with pip I don't have to specify which version of a lib I want to install. If I am running pip3 is the python 3 version, otherwise python 2, assuming both are available

Is the webapp using the optimo app via pip?

**Comment by marzetas** [comment]
a) I don't know, but that approach kind of made sense to me
b) Yes, we install this via pip

**Comment by marzetas** [comment]
Found this guide about how to maintain 2/3 compatibility, perhaps could be of use... https://docs.python.org/3/howto/pyporting.html

**Comment by danmarinescu** [comment]
Seems like the way to achieve this is to handle it in the code. From the guide Raul shared:

> Inevitably you will have code that has to choose what to do based on what version of Python is running. The best way to do this is with feature detection of whether the version of Python you’re running under supports what you need. If for some reason that doesn’t work then you should make the version check be against Python 2 and not Python 3.

**Pull request closed without merging**
